version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  lint-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run prettier:check
      - run: npm run eslint:check
      - run: npm run test
  deploy-functions:
    executor: node/default
    working_directory: ~/project/functions # ensure our steps (except for checkout) run in this directory
    steps:
      - checkout:
          path: ~/project # override the path just for checkout
      - node/install-packages
      - run:
          command: |
            if [ $CIRCLE_BRANCH = "primedre" ]; then
              ENV=prime-dre
            fi
            ./node_modules/.bin/firebase use $ENV --token "$FIREBASE_TOKEN"
            ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_TOKEN"
            ./node_modules/.bin/firebase deploy --only firestore:rules --token "$FIREBASE_TOKEN"
            ./node_modules/.bin/firebase deploy --only storage --token "$FIREBASE_TOKEN"
            ./node_modules/.bin/firebase deploy --only storage:rules --token "$FIREBASE_TOKEN"
  deploy-hosting:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: |
            if [ $CIRCLE_BRANCH = "primedre" ]; then
              PREFIX=PRIMEDRE_
              ENV=prime-dre
              TARGET=prime-dre
              RELEASE_STAGE=prime-dre
            fi

            ./scripts/init-env.sh $PREFIX

            npm run build -- --profile

            ./node_modules/.bin/firebase use $ENV --token "$FIREBASE_TOKEN"
            ./node_modules/.bin/firebase deploy --only hosting:$TARGET --token "$FIREBASE_TOKEN"
workflows:
  build-test-deploy:
    jobs:
      - lint-and-test
      - deploy-functions:
          requires:
            - lint-and-test
          filters:
            branches:
              only:
                - primedre
      - deploy-hosting:
          requires:
            - lint-and-test
          filters:
            branches:
              only:
                - primedre
